type Todo {
  id: String!
  authorEmail: String!
  title: String!
  description: String
  isAllViewPost: Boolean!
  todosSection: String!
  priority: String!
  isComplete: Boolean!
  createdAt: String!
}
